version: 2.1

orbs:
  python: circleci/python@1.2

jobs:
  build:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout  # checkout source code to working directory
      - run:
          command: | 
            sudo pip install --upgrade pip
            sudo pip install -r requirements.txt -f https://download.pytorch.org/whl/cpu/torch_stable.html
            sudo pip install -e .
  # test:
  #   - run:
  #      name: Run tests
  #      command: pytest energy_monitor/tests/misc

workflows:
  build-and-test:
    jobs:
      - build
      # - test
