version: 2.1

workflows:
  sample:
    jobs:
      - build
      - test
      
jobs:
  build:
    docker:
       - image: continuumio/miniconda3
    steps:
      - checkout       # pulls source code to the working directory
      - restore_cache: # restores saved dependency cache if the Branch key template or requirements-test.txt files have not changed since the previous run
          key: deps1-{{ .Branch }}-{{ checksum "requirements-test.txt" }}
      - run:           # install dependencies 
          command: |
            ./install.sh
      - save_cache:    # special step to save dependency cache
          key: deps1-{{ .Branch }}-{{ checksum "requirements-test.txt" }}
          paths: 
            - "venv"
  test:
    steps:
      - run:           # run test suite
          command: |
            ./run_tests.sh
