version: 2.1

workflows:
  sample:
    jobs:
      - build_test
      
jobs:
  build_test:
    docker:
       - image: continuumio/miniconda3
    steps:
      - checkout  # checkout source code to working directory
      - run:
          command: |
            ./install.sh
            # bash run_tests_server.sh
#       - run:
#           command: |  # Run test suite
#            ./run_tests_server.sh
