version: 2.1

workflows:
  sample:
    jobs:
      - build_test
      
jobs:
  build_test:
    docker:
       - image: continuumio/miniconda3
    steps:
      - checkout  # checkout source code to working directory
      # look for existing cache and restore if found
      - restore_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
      # install dependencies 
      - run:
          command: |
            ./install.sh
      # save any changes to the cache
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths: 
            - python_modules  
      # run test suite
      - run:
          command: |
            ./run_tests.sh
