version: 2.1

workflows:
  sample:
    jobs:
      - build_test
      
jobs:
  build_test:
    docker:
       - image: continuumio/miniconda3
    steps:
      - checkout  # checkout source code to working directory
      - run:
          command: |
            ls
            pwd 
            ./setup.sh
      - run:
          command: |  # Run test suite
           # pipenv run pytest
