version: 2.1
      
jobs:
  build_test:
    docker:
       - image: continuumio/miniconda3
    steps:
      - checkout  # checkout source code to working directory
      - run:
          command: |
            ./install.sh
            ./run_tests_server.sh
            
workflows:
  build_test:
    jobs:
      - build_test
      - test
